### ISSUE TITLE
Getting it to work locally

### ISSUE THREAD

**Issue by dorianim** [JanPokorny/speed-climbing-mapping#1]
Hi @JanPokorny 

I just discovered this project, and I am really amazed, it looks great! However, I cannot get the Docker container to build, since the NVIDIA repo in the old TensorFlow container is not available anymore. I also tried using a newer TensorFlow container, but that lead to issues with the python version. 

Any hints on how to fix this?

**Comment by JanPokorny** [comment]
Hello, I've heard about someone having similar problems running this recently. IIRC the trick is that the broken repository isn't really needed, and you can add a command that removes it before the apt update (which installs stuff from the regular Ubuntu repository).

In any case, please send a PR if you make it work

**Comment by dorianim** [comment]
Thanks for the quick reply! I'm still fighting with my Graphics card and Docker, but I'll let you know once I figure it out :)

**Comment by JanPokorny** [comment]
@dorianim Oh yeah, that's an endless battle. I hope you have an Nvidia, other cards are borderline impossible to set-up. You can use this simple test command to see if your GPU passthrough works: `docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody`

I actually developed this on Windows using the GPU passthrough -- nowadays it should work out of the box if you have Windows 11, Docker Desktop and latest Nvidia drivers. (I had a Windows Insider development build at a time, so not sure if it will work on W10.)

Or you can try PopOS, which is an Ubuntu derivative that comes with Nvidia drivers out of the box.

**Comment by JanPokorny** [comment]
(also don't miss that you can get the pre-trained models from the thesis archive: https://is.muni.cz/th/zp7vz/speed-climbing-mapping.zip)

**Comment by dorianim** [comment]
Ok, So I got the container Running (I'm on Archlinux with an Nvidia GPU) by adding
```bash
curl https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub | apt-key add -
```
before the apt update :)

> (also don't miss that you can get the pre-trained models from the thesis archive: https://is.muni.cz/th/zp7vz/speed-climbing-mapping.zip)

Thanks! I'll try to get it working. I'll also leave this issue open in case I hit another roadblock :)
Once I have everything working, I'll open a PR with the fix.

**Comment by dorianim** [comment]
I got it fully working now with two videos of myself, and it looks really promising!

https://github.com/JanPokorny/speed-climbing-mapping/assets/30153207/677a2f04-948f-4751-a4e2-91ea6ecef28b

https://github.com/JanPokorny/speed-climbing-mapping/assets/30153207/6df5540e-c47d-4838-8355-82f2dd4a0b03

Thanks for your help!
